Repository opencloud-eu/opencloud, pull requests merged in 2025-03, with the labels that each got.

#401 posixfs: Use userid as the foldername for personal space
  services/storage-users/pkg/config/defaults/defaultconfig.go
Labels: Type:Bug

#421 feat: clear edition fallback
  services/frontend/pkg/config/defaults/defaultconfig.go
  services/frontend/pkg/revaconfig/config.go
  services/ocdav/pkg/config/defaults/defaultconfig.go
Labels: Type:Maintenance

#446 fix(storage-users): 'uploads sessions' command crash
  services/storage-users/pkg/command/uploads.go
Labels: Type:Bug

#459 fix cli driver initialization for "posix"
  services/storage-users/pkg/command/uploads.go
Labels: Type:Bug

#479 Downgrade nats.go to 1.39.1
  go.mod
  go.sum
  vendor/github.com/nats-io/nats.go/README.md
  vendor/github.com/nats-io/nats.go/go_test.mod
  vendor/github.com/nats-io/nats.go/go_test.sum
  vendor/github.com/nats-io/nats.go/js.go
  vendor/github.com/nats-io/nats.go/jserrors.go
  vendor/github.com/nats-io/nats.go/jsm.go
  vendor/github.com/nats-io/nats.go/kv.go
  vendor/github.com/nats-io/nats.go/nats.go
  vendor/modules.txt
Labels: Type:Bug

#481 fix: add missing debug docker
  .make/go.mk
  opencloud/Makefile
  opencloud/docker/Dockerfile.linux.debug.arm64
Labels: Type:Bug

#483 chore: update alpine to 3.21
  opencloud/docker/Dockerfile.linux.amd64
  opencloud/docker/Dockerfile.linux.arm64
  opencloud/docker/Dockerfile.linux.debug.amd64
  opencloud/docker/Dockerfile.multiarch
Labels: dependencies

#484 Bump golang-jwt/jwt/v4 to 4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: Type:Maintenance

#476 docs(idp): Document how to add custom OIDC clients
  services/idp/README.md
Labels: Type:Documentation

#492 add option to run opencloud_full with decomposed
  deployments/examples/opencloud_full/.env
  deployments/examples/opencloud_full/decomposed.yml
  deployments/examples/opencloud_full/posix.yml
Labels: Type:DevOps

#497 [full-ci] chore(web): update web to v2.1.0
  .woodpecker.env
  services/web/Makefile
Labels: Type:Enhancement

#501 Bump reva to 2.29.1
  go.mod
  go.sum
  tests/acceptance/features/apiAuthApp/token.feature
  vendor/github.com/opencloud-eu/reva/v2/pkg/appauth/manager/jsoncs3/jsoncs3.go
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/pkg/decomposedfs/node/node.go
  vendor/github.com/rs/zerolog/CNAME
  vendor/github.com/rs/zerolog/CONTRIBUTING.md
  vendor/github.com/rs/zerolog/README.md
  vendor/github.com/rs/zerolog/_config.yml
  vendor/github.com/rs/zerolog/console.go
  vendor/github.com/rs/zerolog/log.go
  vendor/github.com/rs/zerolog/sampler.go
  vendor/github.com/rs/zerolog/writer.go
  vendor/modules.txt
Labels: Type:Bug

#494 graph: reduce memory allocations
  services/graph/pkg/service/v0/api_driveitem_permissions.go
  services/graph/pkg/service/v0/api_driveitem_permissions_test.go
  services/graph/pkg/service/v0/base.go
  services/graph/pkg/service/v0/rolemanagement.go
  services/graph/pkg/service/v0/service.go
  services/graph/pkg/service/v0/sharedwithme.go
Labels: Type:Enhancement

#506 update generated code
  docs/apis/grpc_apis/opencloud/messages/eventhistory/v0/grpc.md
  docs/apis/grpc_apis/opencloud/messages/policies/v0/grpc.md
  docs/apis/grpc_apis/opencloud/messages/search/v0/grpc.md
  docs/apis/grpc_apis/opencloud/messages/settings/v0/grpc.md
  docs/apis/grpc_apis/opencloud/messages/store/v0/grpc.md
  docs/apis/grpc_apis/opencloud/messages/thumbnails/v0/grpc.md
  docs/apis/grpc_apis/opencloud/services/eventhistory/v0/grpc.md
  docs/apis/grpc_apis/opencloud/services/policies/v0/grpc.md
  docs/apis/grpc_apis/opencloud/services/search/v0/grpc.md
  docs/apis/grpc_apis/opencloud/services/settings/v0/grpc.md
  docs/apis/grpc_apis/opencloud/services/store/v0/grpc.md
  docs/apis/grpc_apis/opencloud/services/thumbnails/v0/grpc.md
  pkg/kql/dictionary_gen.go
  pkg/oidc/mocks/oidc_client.go
  services/search/pkg/content/mocks/extractor.go
  services/search/pkg/content/mocks/retriever.go
  services/search/pkg/engine/mocks/engine.go
  services/search/pkg/search/mocks/searcher.go
  services/settings/pkg/settings/mocks/manager.go
Labels: Type:Maintenance

#465 add keycloak example
  deployments/examples/opencloud_full/.env
  deployments/examples/opencloud_full/config/keycloak/clients/android_app.json
  deployments/examples/opencloud_full/config/keycloak/clients/cyberduck.json
  deployments/examples/opencloud_full/config/keycloak/clients/desktop_client.json
  deployments/examples/opencloud_full/config/keycloak/clients/ios_app.json
  deployments/examples/opencloud_full/config/keycloak/clients/web.json
  deployments/examples/opencloud_full/config/keycloak/docker-entrypoint-override.sh
  deployments/examples/opencloud_full/config/keycloak/opencloud-realm.dist.json
  deployments/examples/opencloud_full/config/opencloud/csp.yaml
  deployments/examples/opencloud_full/keycloak.yml
Labels: Type:DevOps

#513 add label checker
  .github/workflows/labels.yml
Labels: Type:Maintenance

#535 fix keycloak example #465
  deployments/examples/opencloud_full/keycloak.yml
Labels: Type:Dependencies

#536 feat: change theme.json primary color
  services/web/assets/themes/opencloud/theme.json
Labels: Type:Design, Type:Enhancement

#538 feat: support svg as icon
  services/idp/Makefile
  services/idp/public/index.html
  services/idp/src/images/favicon.ico
  services/idp/src/images/favicon.svg
  services/web/assets/themes/opencloud-dev/assets/favicon.ico
  services/web/assets/themes/opencloud-dev/assets/favicon.svg
  services/web/assets/themes/opencloud-dev/theme.json
  services/web/assets/themes/opencloud/assets/favicon.ico
  services/web/assets/themes/opencloud/assets/favicon.svg
  services/web/assets/themes/opencloud/theme.json
Labels: Type:Design, Type:Enhancement
