Repository opencloud-eu/opencloud, pull requests merged in 2025-08, with the labels that each got.

#1302 Do not run the timout func if the work func has run
  services/search/pkg/search/debouncer.go
  services/search/pkg/search/debouncer_test.go
Labels: Type:Bug

#1332 [decomposed] bump-version-v3.3.0
  pkg/version/version.go
Labels: Type:Dependencies

#1354 feat: add defaultAppId option for the web config.json
  services/web/pkg/config/options.go
Labels: Type:Enhancement

#1350 run CI on cron jobs
  .woodpecker.star
Labels: Type:DevOps

#1352 Dockerfile cleanup
  .dockerignore
  opencloud/Makefile
  opencloud/docker/Dockerfile.linux.amd64
  opencloud/docker/Dockerfile.linux.arm64
  opencloud/docker/Dockerfile.multiarch
Labels: Type:Enhancement

#1377 run also e2e-tests-multi-service pipeline on cron
  .woodpecker.star
Labels: Type:DevOps

#1373 directly connect to frontend
  services/storage-users/pkg/config/defaults/defaultconfig.go
Labels: Type:Enhancement

#1398 [full-ci] run tests with STORAGE_USES_POSIX_WATCH_FS
  .woodpecker.star
Labels: Type:DevOps
