Repository opencloud-eu/opencloud, pull requests merged in 2025-05, with the labels that each got.

#766 [full-ci] chore: bump version v2.29.3
  go.mod
  go.sum
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/pkg/decomposedfs/spaces.go
  vendor/modules.txt
Labels: Type:Maintenance

#672 collaborative posix test
  .woodpecker.star
  tests/acceptance/TestHelpers/CliHelper.php
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/docker/Makefile
  tests/acceptance/docker/src/opencloud-base.yml
  tests/acceptance/docker/src/opencloud.Dockerfile
  tests/acceptance/docker/src/posix.yml
  tests/acceptance/features/collaborativePosix/collaborativePosixFS.feature
  tests/ocwrapper/opencloud/opencloud.go
  tests/ocwrapper/wrapper/handlers/handler.go
Labels: Type:Test

#756 proxy(router): Allow to set some outgoing headers
  pkg/middleware/account.go
  services/activitylog/pkg/service/http.go
  services/auth-app/pkg/service/service.go
  services/graph/pkg/middleware/auth.go
  services/proxy/pkg/command/server.go
  services/proxy/pkg/config/config.go
  services/proxy/pkg/middleware/account_resolver.go
  services/proxy/pkg/middleware/account_resolver_test.go
  services/proxy/pkg/middleware/app_auth.go
  services/proxy/pkg/middleware/app_auth_test.go
  services/proxy/pkg/middleware/authentication_test.go
  services/proxy/pkg/middleware/create_home.go
  services/proxy/pkg/middleware/public_share_auth.go
  services/proxy/pkg/middleware/public_share_auth_test.go
  services/proxy/pkg/router/router.go
Labels: Type:Feature

#773 deployment: Adapt opencloud_full to include radicale
  deployments/examples/opencloud_full/.env
  deployments/examples/opencloud_full/config/opencloud/proxy.yaml
  deployments/examples/opencloud_full/config/radicale/config
  deployments/examples/opencloud_full/radicale.yml
Labels: Type:Feature

#798 chore: remove OO from full deployment example
  deployments/examples/opencloud_full/.env
  deployments/examples/opencloud_full/config/onlyoffice/entrypoint-override.sh
  deployments/examples/opencloud_full/config/onlyoffice/local.json
  deployments/examples/opencloud_full/config/opencloud/csp.yaml
  deployments/examples/opencloud_full/onlyoffice.yml
  deployments/examples/opencloud_full/opencloud.yml
Labels: Type:Maintenance

#780 collaboration posix tests
  .woodpecker.star
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/features/collaborativePosix/collaborativePosixFS.feature
Labels: Type:Test

#782 run ci with decomposed
  .woodpecker.star
  tests/acceptance/expected-failures-localAPI-on-posix-storage.md
Labels: Type:DevOps

#826 [test-only] test for #452
  tests/acceptance/features/apiSpaces/changeSpaces.feature
Labels: Type:Test

#825 nats: Don't enable debug and trace logging by default
  services/nats/pkg/command/server.go
  services/nats/pkg/server/nats/nats.go
Labels: Type:Bug

#833 Switch to opencloud-eu fork of the go-micro nats-js-kv plugin
  go.mod
  go.sum
  vendor/modules.txt
Labels: Type:Maintenance

#843 chore: add idp login text setting to full deployment example
  deployments/examples/opencloud_full/.env
  deployments/examples/opencloud_full/opencloud.yml
  services/idp/src/containers/Login/Login.jsx
Labels: Type:Maintenance

#856 do not skip test on the build binary step
  .woodpecker.star
Labels: Type:DevOps

#837 PosixTest. Check that version, share and link still exist
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/collaborativePosix/collaborativePosixFS.feature
Labels: Type:Test

#849 unnecessary pipeline run in the release ticket
  .woodpecker.star
Labels: Type:DevOps

#884 chore:reva bump v.2.33
  go.mod
  go.sum
  vendor/github.com/segmentio/kafka-go/Makefile
  vendor/github.com/segmentio/kafka-go/README.md
  vendor/github.com/segmentio/kafka-go/batch.go
  vendor/github.com/segmentio/kafka-go/conn.go
  vendor/github.com/segmentio/kafka-go/consumergroup.go
  vendor/github.com/segmentio/kafka-go/createtopics.go
  vendor/github.com/segmentio/kafka-go/deletetopics.go
  vendor/github.com/segmentio/kafka-go/describeclientquotas.go
  vendor/github.com/segmentio/kafka-go/docker-compose-241.yml
  vendor/github.com/segmentio/kafka-go/docker-compose.010.yml
  vendor/github.com/segmentio/kafka-go/docker-compose.yml
  vendor/github.com/segmentio/kafka-go/error.go
  vendor/github.com/segmentio/kafka-go/joingroup.go
  vendor/github.com/segmentio/kafka-go/listgroups.go
  vendor/github.com/segmentio/kafka-go/listoffset.go
  vendor/github.com/segmentio/kafka-go/metadata.go
  vendor/github.com/segmentio/kafka-go/offsetfetch.go
  vendor/github.com/segmentio/kafka-go/protocol/record.go
  vendor/github.com/segmentio/kafka-go/reader.go
  vendor/github.com/segmentio/kafka-go/record.go
  vendor/github.com/segmentio/kafka-go/writer.go
  vendor/modules.txt
Labels: dependencies

#885 [full-ci] chore(web): bump web to v2.3.0
  .woodpecker.env
  services/web/Makefile
Labels: dependencies

#745 🎉 Release 2.3.0
  CHANGELOG.md
Labels: Type:Documentation

#901 graph: move to reva's auto-reconnect LDAP client
  go.mod
  go.sum
  services/graph/pkg/identity/ldap/reconnect.go
  services/graph/pkg/service/v0/service.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go
  vendor/github.com/opencloud-eu/reva/v2/pkg/utils/ldap/reconnect.go
  vendor/modules.txt
Labels: Type:Maintenance

#828 feat: hide close button in collabora
  deployments/examples/opencloud_full/collabora.yml
  services/collaboration/pkg/service/grpc/v0/service.go
  services/collaboration/pkg/service/grpc/v0/service_test.go
  tests/acceptance/features/apiCollaboration/wopi.feature
Labels: Type:Feature

#913 bingo: Remove unneeded dependency on hugo
  .bingo/Variables.mk
  .bingo/hugo.mod
  .bingo/hugo.sum
  .bingo/variables.env
Labels: Type:Maintenance

#916 graph: Add more $select options to ListPermissions endpoint
  services/graph/mocks/drive_item_permissions_provider.go
  services/graph/pkg/service/v0/api_driveitem_permissions.go
  services/graph/pkg/service/v0/api_driveitem_permissions_test.go
  services/graph/pkg/service/v0/utils.go
Labels: Type:Enhancement

#946 fix(graph-metadata): lazy cs3 metadata storage initialization
  pkg/storage/metadata/lazy.go
  pkg/storage/storage.go
  services/graph/pkg/server/http/server.go
  services/graph/pkg/service/v0/api_users_user_profile_photo.go
  services/graph/pkg/service/v0/api_users_user_profile_photo_test.go
  services/graph/pkg/service/v0/application_test.go
  services/graph/pkg/service/v0/approleassignments_test.go
  services/graph/pkg/service/v0/driveitems_test.go
  services/graph/pkg/service/v0/educationclasses_test.go
  services/graph/pkg/service/v0/educationschools_test.go
  services/graph/pkg/service/v0/educationuser_test.go
  services/graph/pkg/service/v0/graph_test.go
  services/graph/pkg/service/v0/groups_test.go
  services/graph/pkg/service/v0/option.go
  services/graph/pkg/service/v0/password_test.go
  services/graph/pkg/service/v0/service.go
  services/graph/pkg/service/v0/sharedbyme_test.go
  services/graph/pkg/service/v0/sharedwithme_test.go
  services/graph/pkg/service/v0/users_test.go
Labels: Type:Bug
