Repository opencloud-eu/opencloud, pull requests merged in 2025-09, with the labels that each got.

#1433 [full-ci] revaBump-2.37.0
  .woodpecker.env
  go.mod
  go.sum
  vendor/github.com/Masterminds/semver/v3/CHANGELOG.md
  vendor/github.com/Masterminds/semver/v3/README.md
  vendor/github.com/Masterminds/semver/v3/constraints.go
  vendor/github.com/Masterminds/semver/v3/version.go
  vendor/github.com/hashicorp/go-plugin/.go-version
  vendor/github.com/hashicorp/go-plugin/CHANGELOG.md
  vendor/github.com/hashicorp/go-plugin/client.go
  vendor/github.com/hashicorp/go-plugin/grpc_broker.go
  vendor/github.com/hashicorp/go-plugin/grpc_client.go
  vendor/github.com/hashicorp/go-plugin/grpc_server.go
  vendor/github.com/hashicorp/go-plugin/grpc_stdio.go
  vendor/github.com/hashicorp/go-plugin/internal/cmdrunner/cmd_reattach.go
  vendor/github.com/hashicorp/go-plugin/internal/cmdrunner/cmd_runner.go
  vendor/github.com/hashicorp/go-plugin/internal/cmdrunner/notes_unix.go
  vendor/github.com/hashicorp/go-plugin/log_entry.go
  vendor/github.com/hashicorp/go-plugin/mux_broker.go
  vendor/github.com/hashicorp/go-plugin/rpc_client.go
  vendor/github.com/hashicorp/go-plugin/rpc_server.go
  vendor/github.com/hashicorp/go-plugin/server.go
  vendor/github.com/hashicorp/go-plugin/testing.go
  vendor/github.com/hashicorp/yamux/LICENSE
  vendor/github.com/hashicorp/yamux/mux.go
  vendor/github.com/hashicorp/yamux/session.go
  vendor/github.com/hashicorp/yamux/spec.md
  vendor/github.com/hashicorp/yamux/stream.go
  vendor/github.com/hashicorp/yamux/util.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/reporters/default_reporter.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/internal/async_assertion.go
  vendor/github.com/onsi/gomega/matchers/be_comparable_to_matcher.go
  vendor/github.com/onsi/gomega/matchers/match_yaml_matcher.go
  vendor/github.com/opencloud-eu/reva/v2/pkg/owncloud/ocs/capabilities.go
  vendor/github.com/segmentio/kafka-go/docker-compose.yml
  vendor/github.com/segmentio/kafka-go/listgroups.go
  vendor/github.com/segmentio/kafka-go/protocol/offsetcommit/offsetcommit.go
  vendor/go.yaml.in/yaml/v3/LICENSE
  vendor/go.yaml.in/yaml/v3/NOTICE
  vendor/go.yaml.in/yaml/v3/README.md
  vendor/go.yaml.in/yaml/v3/apic.go
  vendor/go.yaml.in/yaml/v3/decode.go
  vendor/go.yaml.in/yaml/v3/emitterc.go
  vendor/go.yaml.in/yaml/v3/encode.go
  vendor/go.yaml.in/yaml/v3/parserc.go
  vendor/go.yaml.in/yaml/v3/readerc.go
  vendor/go.yaml.in/yaml/v3/resolve.go
  vendor/go.yaml.in/yaml/v3/scannerc.go
  vendor/go.yaml.in/yaml/v3/sorter.go
  vendor/go.yaml.in/yaml/v3/writerc.go
  vendor/go.yaml.in/yaml/v3/yaml.go
  vendor/go.yaml.in/yaml/v3/yamlh.go
  vendor/go.yaml.in/yaml/v3/yamlprivateh.go
  vendor/modules.txt
Labels: Type:Dependencies

#1334 🎉 Release 3.4.0
  CHANGELOG.md
Labels: Type:Documentation

#1403 [full-ci] purge browsers, opencloud web and playwright tracing cache
  .woodpecker.star
Labels: Type:Test

#1436 Tracing improvements
  services/graph/pkg/service/v0/service.go
  services/proxy/pkg/command/server.go
  services/proxy/pkg/middleware/account_resolver.go
  services/proxy/pkg/middleware/authentication.go
  services/proxy/pkg/middleware/create_home.go
  services/proxy/pkg/middleware/policies.go
  services/proxy/pkg/middleware/selector_cookie.go
  services/proxy/pkg/middleware/tracing.go
Labels: Type:Enhancement

#1420 [full-ci] run tests with VIPS enabled
  .woodpecker.star
  tests/acceptance/expected-failures-API-on-decomposed-storage.md
  tests/acceptance/expected-failures-API-on-posix-storage.md
  tests/acceptance/expected-failures-localAPI-on-decomposed-storage.md
  tests/acceptance/features/coreApiWebdavPreviews/previews.feature
  tests/acceptance/features/coreApiWebdavPreviews/previewsAutoAdustedSizing.feature
  tests/acceptance/fixtures/fill.png
  tests/acceptance/fixtures/fit.png
  tests/acceptance/fixtures/resize.png
  tests/acceptance/fixtures/text-file-fixture.png
  tests/acceptance/fixtures/thumbnail.png
  tests/acceptance/fixtures/unicode-fixture.png
Labels: Type:Test

#1474 remove opencloud_full from the read.me and add opencloud-compose instead
  deployments/examples/opencloud_full/.env
  deployments/examples/opencloud_full/config/keycloak/clients/web.json
  services/app-registry/README.md
  services/proxy/README.md
  services/search/README.md
Labels: Type:Documentation

#1485 fix: re-generate mocks for search service
  services/search/pkg/search/mocks/batch_operator.go
  services/search/pkg/search/mocks/engine.go
  services/search/pkg/search/mocks/searcher.go
Labels: Type:Maintenance

#1507 [full-ci][tests-only] revert behat version and fix regex on test script
  tests/acceptance/run.sh
  vendor-bin/behat/composer.json
Labels: Type:Test

#1516 fix(search): readme typos and mention the lack of scalability
  services/search/README.md
Labels: Type:Documentation

#1520 enhancement(docs): add branch naming styleguide and clean up the contribution guidelines
  CONTRIBUTING.md
Labels: Type:Documentation

#1500 chore(web): remove unused theming options
  services/web/assets/themes/opencloud-dev/theme.json
  services/web/assets/themes/opencloud/theme.json
Labels: Type:Maintenance

#1530 revaBump-2.38.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: Type:Dependencies

#1532 [decomposed] bump-version-v3.5.0
  pkg/version/version.go
Labels: Type:Dependencies

#1444 🎉 Release 3.5.0
  CHANGELOG.md
Labels: Type:Documentation

#1533 use correct endpoint in nats check
  services/proxy/pkg/server/debug/server.go
  tests/acceptance/expected-failures-localAPI-on-decomposed-storage.md
  tests/acceptance/expected-failures-localAPI-on-posix-storage.md
Labels: Type:Bug, Status:In-Progress

#1550 apiTest-flaky: sync share before checking
  tests/acceptance/features/apiSharingNgShareInvitation/shareInvitations.feature
Labels: Type:Test

#1542 introduce AppURLs helper for atomic backgroud updates
  services/collaboration/pkg/command/server.go
  services/collaboration/pkg/helpers/discovery.go
  services/collaboration/pkg/helpers/discovery_test.go
  services/collaboration/pkg/helpers/registration.go
  services/collaboration/pkg/server/grpc/option.go
  services/collaboration/pkg/service/grpc/v0/option.go
  services/collaboration/pkg/service/grpc/v0/service.go
  services/collaboration/pkg/service/grpc/v0/service_test.go
Labels: Type:Enhancement

#1565 let the runtime always create a cancel context
  opencloud/pkg/runtime/service/service.go
Labels: Type:Bug

#1553 [full-ci] getting personal space by userId instead of userName
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/bootstrap/CliContext.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/bootstrap/GraphContext.php
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/features/apiActivities/activities.feature
  tests/acceptance/features/apiGraph/userGDPRExport.feature
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/coreApiWebdavProperties/getQuota.feature
Labels: Type:Test

#1588 fix: use valid autocomplete values (axe autocomplete-valid)
  services/idp/src/containers/Login/Login.jsx
Labels: Type:Bug

#1574 [full-ci] Enhance getSpaceByName: check local cache before Graph API calls
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/bootstrap/SpacesContext.php
  tests/acceptance/expected-failures-without-remotephp.md
  tests/acceptance/features/apiCors/cors.feature
  tests/acceptance/features/apiGraph/userGDPRExport.feature
  tests/acceptance/features/apiLocks/lockFiles.feature
  tests/acceptance/features/apiLocks/unlockFiles.feature
  tests/acceptance/features/apiSearch1/search.feature
  tests/acceptance/features/apiSpaces/changeSpaces.feature
  tests/acceptance/features/apiSpaces/quota.feature
  tests/acceptance/features/apiSpaces/setQuota.feature
  tests/acceptance/features/apiSpaces/tag.feature
  tests/acceptance/features/apiSpaces/tusUpload.feature
  tests/acceptance/features/apiSpacesShares/shareOperations.feature
  tests/acceptance/features/coreApiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/coreApiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/coreApiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/coreApiWebdavProperties/getQuota.feature
Labels: Type:Test
