Repository opencloud-eu/opencloud, pull requests merged in 2025-04, with the labels that each got.

#545 chore: bump unzip extension to v1.0.2
  deployments/examples/opencloud_full/web_extensions/unzip.yml
Labels: Type:Maintenance

#546 Enable scan/watch in the storageprovider only
  services/storage-users/pkg/command/uploads.go
  services/storage-users/pkg/revaconfig/drivers.go
  services/storage-users/pkg/revaconfig/user.go
Labels: Type:Bug

#549 fix: correct daily version
  .make/go.mk
  pkg/version/version.go
Labels: Type:Maintenance

#555 fix: traefik credentials
  deployments/examples/opencloud_full/.env
Labels: Type:Bug

#553 fix: full deployment tika description is wrong
  deployments/examples/opencloud_full/.env
Labels: Type:Bug

#561 Revert "Disable the 'exclude' patterns on the path conditional for now"
  .woodpecker.star
Labels: Type:DevOps, Type:Test

#564 ci: Allow the `Type:DevOps` label
  .github/workflows/labels.yml
Labels: Type:DevOps

#563 fix(opencloud_full): add missing SMTP env vars
  deployments/examples/opencloud_full/.env
  deployments/examples/opencloud_full/opencloud.yml
Labels: Type:Bug

#570 [full-ci] chore(web): bump web to v2.2.0
  .woodpecker.env
  services/web/Makefile
Labels: Type:Dependencies

#596 [full-ci] fix expected spanish string in test
  tests/acceptance/expected-failures-localAPI-on-decomposed-storage.md
  tests/acceptance/features/apiAntivirus/antivirus.feature
Labels: Type:Test

#591 [full-ci] remove unneeded variables
  .woodpecker.star
Labels: Type:DevOps

#592 [full-ci] Remove unneeded parentheses
  .woodpecker.star
Labels: Type:DevOps

#589 Harmonize Keycloak Client Configurations with Built-in IdP
  deployments/examples/opencloud_full/config/keycloak/clients/OpenCloudAndroid.json
  deployments/examples/opencloud_full/config/keycloak/clients/OpenCloudDesktop.json
  deployments/examples/opencloud_full/config/keycloak/clients/OpenCloudIOS.json
  deployments/examples/opencloud_full/config/keycloak/clients/cyberduck.json
  deployments/examples/opencloud_full/config/keycloak/clients/web.json
  deployments/examples/opencloud_full/config/keycloak/opencloud-realm.dist.json
Labels: Type:DevOps

#559 feat(antivirus): add partial scanning mode
  deployments/examples/opencloud_full/.env
  deployments/examples/opencloud_full/clamav.yml
  services/antivirus/README.md
  services/antivirus/pkg/command/server.go
  services/antivirus/pkg/config/config.go
  services/antivirus/pkg/config/defaults/defaultconfig.go
  services/antivirus/pkg/scanners/clamav.go
  services/antivirus/pkg/scanners/clamav_test.go
  services/antivirus/pkg/scanners/scanners.go
  services/antivirus/pkg/service/service.go
Labels: Type:Bug

#504 🎉 Release 2.1.0
  CHANGELOG.md
Labels: Type:Documentation

#594 [full-ci] only use wrapper when requested
  .woodpecker.star
Labels: Type:DevOps

#614 chore: bump version to v2.1.0
  pkg/version/version.go
Labels: Type:Enhancement

#617 feat: improve the info about storage path in deployment example
  deployments/examples/opencloud_full/.env
Labels: Status:Needs-Review, Type:Feature

#601 revert: completely remove "edition" from capabilities
  services/frontend/pkg/config/config.go
  services/frontend/pkg/config/defaults/defaultconfig.go
  services/frontend/pkg/revaconfig/config.go
  services/ocdav/pkg/command/server.go
  services/ocdav/pkg/config/config.go
  services/ocdav/pkg/config/defaults/defaultconfig.go
  tests/acceptance/bootstrap/CapabilitiesContext.php
  tests/acceptance/bootstrap/FeatureContext.php
  tests/acceptance/features/coreApiCapabilities/capabilities.feature
  tests/acceptance/features/coreApiCapabilities/capabilitiesWithNormalUser.feature
  tests/acceptance/features/coreApiMain/status.feature
Labels: Type:Enhancement

#619 fix inbucket setup
  deployments/examples/opencloud_full/opencloud.yml
Labels: Type:Bug

#633 fix: web dev docs broken links
  docs/20-web/50-extension-system/index.md
Labels: Type:Bug, Type:Documentation

#569 example Ldap setup
  deployments/examples/opencloud_full/.env
  deployments/examples/opencloud_full/config/ldap/docker-entrypoint-override.sh
  deployments/examples/opencloud_full/config/ldap/ldif/10_base.ldif
  deployments/examples/opencloud_full/config/ldap/ldif/20_users.ldif
  deployments/examples/opencloud_full/config/ldap/ldif/30_groups.ldif
  deployments/examples/opencloud_full/ldap.yml
  deployments/examples/shared/config/ldap/docker-compose.yml
Labels: Type:DevOps

#635 chore: move dev docs to opencloud-eu/docs repo
  .woodpecker/docs.yaml
  docs/20-web/10-getting-started.md
  docs/20-web/20-development/10-conventions.md
  docs/20-web/20-development/20-repo-structure.md
  docs/20-web/20-development/30-tooling.md
  docs/20-web/20-development/_category_.json
  docs/20-web/20-development/index.md
  docs/20-web/30-testing/10-running-tests.md
  docs/20-web/30-testing/20-e2e-testing-standards.md
  docs/20-web/30-testing/_category_.json
  docs/20-web/30-testing/index.md
  docs/20-web/40-embed-mode/_category_.json
  docs/20-web/40-embed-mode/index.md
  docs/20-web/50-extension-system/10-viewer-editor-apps.md
  docs/20-web/50-extension-system/20-extension-types/10-action-extensions.md
  docs/20-web/50-extension-system/20-extension-types/20-app-menu-item-extensions.md
  docs/20-web/50-extension-system/20-extension-types/30-custom-component-extensions.md
  docs/20-web/50-extension-system/20-extension-types/40-folder-view-extensions.md
  docs/20-web/50-extension-system/20-extension-types/50-left-sidebar-menu-item-extensions.md
  docs/20-web/50-extension-system/20-extension-types/60-right-sidebar-panel-extensions.md
  docs/20-web/50-extension-system/20-extension-types/70-search-extensions.md
  docs/20-web/50-extension-system/20-extension-types/_category_.json
  docs/20-web/50-extension-system/20-extension-types/index.md
  docs/20-web/50-extension-system/_category_.json
  docs/20-web/50-extension-system/index.md
  docs/20-web/_category_.json
  docs/20-web/index.md
  docs/intro.md
Labels: Type:Maintenance, Type:Documentation

#638 [full-ci] chore(web): bump web to v2.1.1
  .woodpecker.env
  services/web/Makefile
Labels: Type:Enhancement

#620 fix(antivirus | backport): introduce a default max scan size for the full example deployment
  deployments/examples/opencloud_full/.env
  deployments/examples/opencloud_full/clamav.yml
  services/antivirus/README.md
  services/antivirus/pkg/config/config.go
Labels: Type:Bug

#660 Check that clamav is ready before the server run
  .woodpecker.star
Labels: Type:DevOps

#652 update test docs
  tests/README.md
  tests/acceptance/run_api_tests.sh
Labels: Type:Test

#618 [full-ci]Remove code duplication from starlark
  .woodpecker.star
Labels: Type:DevOps

#574 Feat: install.sh now honors OC_BASE_DIR and OC_HOST
  deployments/examples/bare-metal-simple/README.md
  deployments/examples/bare-metal-simple/install.sh
Labels: Type:Enhancement

#671 fix deployment: do not create demo accounts when using keycloak
  deployments/examples/opencloud_full/keycloak.yml
Labels: Type:Bug

#611 [full-ci] delete unneeded containers and directories
  .woodpecker.star
Labels: Type:DevOps

#665 feat(web): remove old and unused color tokens
  services/web/assets/themes/opencloud/theme.json
Labels: Type:Enhancement

#552 Add env var to make the inotify stats frequency configurable
  services/storage-users/pkg/config/config.go
  services/storage-users/pkg/config/defaults/defaultconfig.go
  services/storage-users/pkg/revaconfig/drivers.go
Labels: Type:Enhancement

#669 Expose more config vars for the posix fs watchers
  services/storage-users/pkg/config/config.go
  services/storage-users/pkg/revaconfig/drivers.go
Labels: Type:Enhancement

#680 ci: make release plugin compatible with stable branch workflow
  release-config.ts
Labels: Type:DevOps

#688 fix: labels bot needs token for forks
  .github/workflows/labels.yml
Labels: Type:DevOps

#681 chore: bump reva to v2.29.2
  go.mod
  go.sum
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/fs/posix/lookup/lookup.go
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/pkg/decomposedfs/metadata/hybrid_backend.go
  vendor/modules.txt
Labels: Type:Dependencies

#689 Port #567
  vendor/github.com/nats-io/nats.go/README.md
  vendor/github.com/nats-io/nats.go/go_test.mod
  vendor/github.com/nats-io/nats.go/go_test.sum
  vendor/github.com/nats-io/nats.go/js.go
  vendor/github.com/nats-io/nats.go/jserrors.go
  vendor/github.com/nats-io/nats.go/jsm.go
  vendor/github.com/nats-io/nats.go/kv.go
  vendor/github.com/nats-io/nats.go/nats.go
  vendor/github.com/nats-io/nats.go/object.go
  vendor/modules.txt
Labels: Type:Dependencies, dependencies, go

#692 chore: fix app provider default names in opencloud_full deployment
  deployments/examples/opencloud_full/config/opencloud/app-registry.yaml
Labels: Type:Maintenance

#643 Fix broken links in opencloud_full README.md
  .github/workflows/labels.yml
  deployments/examples/opencloud_full/README.md
Labels: Type:Documentation

#693 fix: binary release version
  .woodpecker.star
Labels: Type:DevOps

#694 fix(decomposeds3): enable async-uploads by default (#686)
  services/storage-users/pkg/config/defaults/defaultconfig.go
Labels: Type:Bug

#695 fix: binary release version
  .woodpecker.star
Labels: Type:DevOps

#698 chore: remove docs workflows
  .woodpecker.star
  .woodpecker/docs.yaml
Labels: Type:DevOps

#709 Some smaller Makefile adjustments
  .make/recursion.mk
  Makefile
  opencloud/Makefile
  pkg/Makefile
  protogen/Makefile
  services/activitylog/Makefile
  services/antivirus/Makefile
  services/app-provider/Makefile
  services/app-registry/Makefile
  services/audit/Makefile
  services/auth-app/Makefile
  services/auth-basic/Makefile
  services/auth-bearer/Makefile
  services/auth-machine/Makefile
  services/auth-service/Makefile
  services/clientlog/Makefile
  services/collaboration/Makefile
  services/eventhistory/Makefile
  services/frontend/Makefile
  services/gateway/Makefile
  services/graph/Makefile
  services/groups/Makefile
  services/idm/Makefile
  services/idp/Makefile
  services/invitations/Makefile
  services/nats/Makefile
  services/notifications/Makefile
  services/ocdav/Makefile
  services/ocm/Makefile
  services/ocs/Makefile
  services/policies/Makefile
  services/postprocessing/Makefile
  services/proxy/Makefile
  services/search/Makefile
  services/settings/Makefile
  services/sharing/Makefile
  services/sse/Makefile
  services/storage-publiclink/Makefile
  services/storage-shares/Makefile
  services/storage-system/Makefile
  services/storage-users/Makefile
  services/thumbnails/Makefile
  services/userlog/Makefile
  services/users/Makefile
  services/web/Makefile
  services/webdav/Makefile
  services/webfinger/Makefile
Labels: Type:Bug

#724 Update descirption of COLLABORA_SSL_ENABLE
  deployments/examples/opencloud_full/.env
Labels: Type:Documentation

#731 chore: prepare release, bump version
  pkg/version/version.go
Labels: Type:Dependencies

#640 🎉 Release 2.0.1
  CHANGELOG.md
Labels: Type:Documentation

#737 chore:reva bump v.2.32
  go.mod
  go.sum
  vendor/github.com/ceph/go-ceph/cephfs/directory.go
  vendor/github.com/ceph/go-ceph/cephfs/errors.go
  vendor/github.com/ceph/go-ceph/cephfs/file.go
  vendor/github.com/ceph/go-ceph/cephfs/fscompat.go
  vendor/github.com/ceph/go-ceph/rados/rados_getaddrs.go
  vendor/github.com/go-sql-driver/mysql/CHANGELOG.md
  vendor/github.com/opencloud-eu/reva/v2/internal/http/services/owncloud/ocdav/copy.go
  vendor/github.com/opencloud-eu/reva/v2/internal/http/services/owncloud/ocdav/delete.go
  vendor/github.com/opencloud-eu/reva/v2/internal/http/services/owncloud/ocdav/mkcol.go
  vendor/github.com/opencloud-eu/reva/v2/internal/http/services/owncloud/ocdav/move.go
  vendor/github.com/opencloud-eu/reva/v2/internal/http/services/owncloud/ocdav/ocdav.go
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/fs/posix/lookup/lookup.go
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/fs/posix/options/options.go
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/fs/posix/tree/assimilation.go
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/fs/posix/tree/cephfswatcher.go
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/fs/posix/tree/gpfswatchfolderwatcher.go
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/fs/posix/tree/tree.go
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/pkg/decomposedfs/metadata/hybrid_backend.go
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/pkg/decomposedfs/upload/upload.go
  vendor/github.com/prometheus/client_golang/prometheus/collectorfunc.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/internal/compression.go
  vendor/modules.txt
Labels: Type:Dependencies

#738 [full-ci] chore(web): bump web to v2.3.0
  .woodpecker.env
  services/web/Makefile
Labels: Type:Enhancement

#739 chore: bump version v2.2.0
  pkg/version/version.go
Labels: Type:Maintenance

#613 🎉 Release 2.2.0
  CHANGELOG.md
Labels: Type:Documentation

#742 fix: idp login logo url exceeds logo
  services/idp/src/app.css
  services/idp/src/components/ResponsiveScreen.jsx
Labels: Type:Bug

#748 fix mockery warnings
  pkg/.mockery.yaml
  pkg/oidc/mocks/oidc_client.go
  protogen/.mockery.yaml
  services/antivirus/.mockery.yaml
  services/antivirus/pkg/scanners/mocks/scanner.go
  services/collaboration/.mockery.yaml
  services/collaboration/mocks/connector_service.go
  services/collaboration/mocks/content_connector_service.go
  services/collaboration/mocks/file_connector_service.go
  services/collaboration/mocks/gateway_selector.go
  services/collaboration/mocks/lock_parser.go
  services/graph/.mockery.yaml
  services/graph/mocks/base_graph_provider.go
  services/graph/mocks/drive_item_permissions_provider.go
  services/graph/mocks/drives_drive_item_provider.go
  services/graph/mocks/gateway_selector.go
  services/graph/mocks/http_client.go
  services/graph/mocks/permissions.go
  services/graph/mocks/publisher.go
  services/graph/mocks/role_service.go
  services/graph/pkg/identity/mocks/backend.go
  services/graph/pkg/identity/mocks/education_backend.go
  services/graph/pkg/identity/mocks/ldapclient.go
  services/invitations/.mockery.yaml
  services/invitations/pkg/backends/keycloak/mocks/client.go
  services/proxy/.mockery.yaml
  services/proxy/pkg/user/backend/mocks/user_backend.go
  services/proxy/pkg/userroles/mocks/user_role_assigner.go
  services/search/.mockery.yaml
  services/search/pkg/content/mocks/extractor.go
  services/search/pkg/content/mocks/retriever.go
  services/search/pkg/engine/mocks/engine.go
  services/search/pkg/search/mocks/searcher.go
  services/settings/.mockery.yaml
  services/settings/pkg/settings/mocks/manager.go
Labels: Type:Maintenance

#720 Supported production setup with Keycloak and LDAP
  deployments/examples/opencloud_full/.env
  deployments/examples/opencloud_full/config/keycloak/opencloud-realm.dist.json
  deployments/examples/opencloud_full/ldap.yml
Labels: Type:DevOps

#746 feat: set idp logo defaul url
  services/idp/pkg/config/defaults/defaultconfig.go
Labels: Type:Feature
