Repository opencloud-eu/opencloud, pull requests merged in 2025-06, with the labels that each got.

#972 [full-ci] chore: bump web to v3.0.0-alpha.1
  .woodpecker.env
  services/web/Makefile
Labels: Type:Enhancement

#983 Enhancement: Introduced support for PrivateLink in WebDAV search responses
  services/webdav/pkg/config/defaults/defaultconfig.go
  services/webdav/pkg/service/v0/search.go
Labels: Type:Feature

#992 [full-ci] Change `eicar_com.zip` virus file and update tests
  tests/acceptance/expected-failures-localAPI-on-decomposed-storage.md
  tests/acceptance/expected-failures-localAPI-on-posix-storage.md
  tests/acceptance/expected-failures-without-remotephp.md
  tests/acceptance/features/apiAntivirus/antivirus.feature
  tests/acceptance/filesForUpload/filesWithVirus/eicar_com.zip
Labels: Type:Test

#942 apiTest. select option for root/permissions endpoint
  tests/acceptance/TestHelpers/GraphHelper.php
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/features/apiSharingNg1/listPermissions.feature
Labels: Type:Test

#1026 [full-ci] chore: bump web to v3.0.0
  .woodpecker.env
  services/web/Makefile
Labels: Type:Enhancement

#1027 [full-ci] chore:reva bump v.2.33.1
  go.mod
  go.sum
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/fs/posix/tree/tree.go
  vendor/github.com/pkg/xattr/xattr_solaris.go
  vendor/golang.org/x/crypto/bcrypt/bcrypt.go
  vendor/golang.org/x/crypto/ssh/agent/client.go
  vendor/golang.org/x/crypto/ssh/agent/server.go
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/connection.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/crypto/ssh/mac.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/mlkem.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/modules.txt
Labels: dependencies

#996 graph: Add $filter to only list (and/or count) member permissions
  services/graph/pkg/service/v0/api_driveitem_permissions.go
  services/graph/pkg/service/v0/api_driveitem_permissions_test.go
Labels: Type:Enhancement

#1030 [decomposed] bump-version-v3.0.0
  pkg/version/version.go
Labels: Status:Needs-Review, dependencies

#943 fix(docs): WEB_ASSET_PATH was still mentioned in the web readme
  services/web/README.md
Labels: Type:Documentation

#1070 build: Modify mockery config to work with v3
  .bingo/Variables.mk
  .bingo/mockery.mod
  .bingo/mockery.sum
  .bingo/variables.env
  .editorconfig
  Makefile
  pkg/.mockery.yaml
  pkg/oidc/mocks/oidc_client.go
  protogen/.mockery.yaml
  protogen/Makefile
  protogen/gen/opencloud/services/eventhistory/v0/mocks/event_history_service.go
  protogen/gen/opencloud/services/policies/v0/mocks/policies_provider_service.go
  protogen/gen/opencloud/services/search/v0/mocks/search_provider_service.go
  protogen/gen/opencloud/services/settings/v0/mocks/value_service.go
  protogen/gen/opencloud/services/thumbnails/v0/mocks/thumbnail_service.go
  services/antivirus/.mockery.yaml
  services/antivirus/pkg/scanners/mocks/scanner.go
  services/collaboration/.mockery.yaml
  services/collaboration/mocks/connector_service.go
  services/collaboration/mocks/content_connector_service.go
  services/collaboration/mocks/file_connector_service.go
  services/collaboration/mocks/gateway_selector.go
  services/collaboration/mocks/lock_parser.go
  services/graph/.mockery.yaml
  services/graph/mocks/base_graph_provider.go
  services/graph/mocks/drive_item_permissions_provider.go
  services/graph/mocks/drives_drive_item_provider.go
  services/graph/mocks/gateway_selector.go
  services/graph/mocks/http_client.go
  services/graph/mocks/permissions.go
  services/graph/mocks/publisher.go
  services/graph/mocks/role_service.go
  services/graph/mocks/storage.go
  services/graph/mocks/users_user_profile_photo_provider.go
  services/graph/pkg/identity/mocks/backend.go
  services/graph/pkg/identity/mocks/education_backend.go
  services/graph/pkg/identity/mocks/ldapclient.go
  services/invitations/.mockery.yaml
  services/invitations/pkg/backends/keycloak/mocks/client.go
  services/proxy/.mockery.yaml
  services/proxy/pkg/user/backend/mocks/user_backend.go
  services/proxy/pkg/userroles/mocks/user_role_assigner.go
  services/search/.mockery.yaml
  services/search/pkg/content/mocks/extractor.go
  services/search/pkg/content/mocks/retriever.go
  services/search/pkg/engine/mocks/engine.go
  services/search/pkg/search/mocks/searcher.go
  services/settings/.mockery.yaml
  services/settings/pkg/settings/mocks/manager.go
Labels: Type:Maintenance

#1077 Update the href of CONTRIBUTING to the dev docs
  CONTRIBUTING.md
Labels: Type:Documentation

#1086 fix: collabora use metrics instead of imperial metric system
  services/collaboration/pkg/service/grpc/v0/service.go
  services/collaboration/pkg/service/grpc/v0/service_test.go
Labels: Type:Bug

#1098 feat: adjust space template image to match brand color
  .woodpecker.star
  services/graph/pkg/service/v0/spacetemplate/image.png
Labels: Type:Feature

#1108 feat: add accessibility url to theme.json files
  services/web/assets/themes/opencloud-dev/theme.json
  services/web/assets/themes/opencloud/theme.json
Labels: Type:Enhancement

#1119 feat: re-enable Save As and Export in collabora
  services/collaboration/pkg/connector/fileconnector.go
  services/collaboration/pkg/connector/fileconnector_test.go
  services/collaboration/pkg/connector/fileinfo/collabora.go
  tests/acceptance/features/apiCollaboration/checkFileInfo.feature
Labels: Type:Enhancement

#1127 Only remove obsolete IDs from the index
  opencloud/pkg/command/posixfs.go
Labels: Type:Bug

#1142 [decomposed] bump-version-v3.1.0
  pkg/version/version.go
Labels: Status:Needs-Review, dependencies
