Repository opencloud-eu/opencloud, pull requests merged in 2025-07, with the labels that each got.

#1035 fix(collaboration): re register app providers in a configurable interval
  services/collaboration/pkg/command/server.go
  services/collaboration/pkg/config/cs3api.go
  services/collaboration/pkg/config/defaults/defaultconfig.go
Labels: Type:Bug

#1187 Update Makefile
  Makefile
Labels: Type:Bug

#1203 get hostname of S3 server from var. not secret
  .woodpecker.star
Labels: Type:DevOps

#1202 [full-ci] Reva bump 2.29.4
  go.mod
  go.sum
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/pkg/decomposedfs/node/node.go
  vendor/modules.txt
Labels: dependencies

#1204 🎉 Release 2.0.3
  CHANGELOG.md
Labels: Type:Documentation

#1188 feat(web): add dark mode and adjust light theme colors
  services/web/assets/themes/opencloud/assets/logo-white.svg
  services/web/assets/themes/opencloud/theme.json
Labels: Type:Enhancement

#1210 fix: build args are now an object
  .woodpecker.star
Labels: Type:DevOps

#1189 revert #1187 and add a NOOP clean step to `protogen/Makefile`
  Makefile
  protogen/Makefile
Labels: Type:Maintenance

#1214 🎉 Release 2.0.4
  CHANGELOG.md
Labels: Type:Documentation

#1236 tests: Avoid static dates when creating shares
  tests/acceptance/bootstrap/SharingNgContext.php
  tests/acceptance/features/apiSharingNgShareInvitation/updateShareInvitations.feature
Labels: Type:Maintenance

#1191 proxy(sign_url_auth): Allow to verify server signed URLs
  services/ocdav/pkg/command/server.go
  services/ocdav/pkg/config/config.go
  services/proxy/pkg/command/server.go
  services/proxy/pkg/config/config.go
  services/proxy/pkg/middleware/signed_url_auth.go
  services/proxy/pkg/middleware/signed_url_auth_test.go
Labels: Type:Enhancement

#1255 [full-ci] Reva bump 2.35.0
  go.mod
  go.sum
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/fs/posix/trashbin/trashbin.go
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/fs/posix/tree/assimilation.go
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/fs/posix/tree/tree.go
  vendor/github.com/opencloud-eu/reva/v2/pkg/storage/utils/templates/templates.go
  vendor/modules.txt
Labels: Type:Dependencies

#1253 [full-ci] chore: bump web to v3.2.0
  .woodpecker.env
  services/web/Makefile
Labels: Type:Enhancement

#1240 [with-tracing] cache browsers and use chromium for web-e2e-tests
  .woodpecker.env
  .woodpecker.star
Labels: Type:DevOps

#1259 🎉 Release 3.2.1
  CHANGELOG.md
Labels: Type:Documentation
